"""preserve contributor merge history for unmerge

Revision ID: 8d54a3cb31d1
Revises: 0013
Create Date: 2026-09-10 19:49:23.897604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d54a3cb31d1'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('merge_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'merge_history')
    # ### end Alembic commands ###
